# Generated by Django 3.1.4 on 2020-12-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronix_radio', '0002_auto_20201216_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
