# Generated by Django 3.1.4 on 2020-12-20 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronix_radio', '0003_song_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='favourite',
            new_name='is_favourite',
        ),
    ]
