# Generated by Django 3.1.4 on 2020-12-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronix_radio', '0006_auto_20201229_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronixAggression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_time', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='ChronixGrit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_time', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='ChronixMetal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_time', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='ChronixRadio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_time', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=100)),
                ('artist_name', models.CharField(max_length=100)),
                ('album_name', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('favourite', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.AddField(
            model_name='chronixradio',
            name='track',
            field=models.ManyToManyField(to='chronix_radio.Tracks'),
        ),
        migrations.AddField(
            model_name='chronixmetal',
            name='track',
            field=models.ManyToManyField(to='chronix_radio.Tracks'),
        ),
        migrations.AddField(
            model_name='chronixgrit',
            name='track',
            field=models.ManyToManyField(to='chronix_radio.Tracks'),
        ),
        migrations.AddField(
            model_name='chronixaggression',
            name='track',
            field=models.ManyToManyField(to='chronix_radio.Tracks'),
        ),
    ]
