# Generated by Django 3.1.4 on 2020-12-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronix_radio', '0008_auto_20201229_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='favourite',
            field=models.BooleanField(blank=True, choices=[('T', 'True'), ('F', 'False')], default=False),
        ),
    ]
