# Generated by Django 3.1.4 on 2020-12-31 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronix_radio', '0009_auto_20201229_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='album_name',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='artist_name',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='track_name',
            new_name='title',
        ),
    ]
