# Generated by Django 3.1.4 on 2020-12-16 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronix_aggression', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='album',
            new_name='album_text',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artist',
            new_name='artist_text',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='name',
            new_name='name_text',
        ),
    ]
