# Generated by Django 3.1.4 on 2020-12-20 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronix_aggression', '0004_auto_20201220_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='name_text',
            new_name='track_text',
        ),
    ]
