# Generated by Django 3.1.5 on 2021-01-12 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('radio_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronixMetalTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_time', models.DateTimeField(verbose_name='date published')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='radio_hub.track')),
            ],
        ),
        migrations.CreateModel(
            name='ChronixGritTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_time', models.DateTimeField(verbose_name='date published')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='radio_hub.track')),
            ],
        ),
        migrations.CreateModel(
            name='ChronixAggressionTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_time', models.DateTimeField(verbose_name='date published')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='radio_hub.track')),
            ],
        ),
    ]
